fields:
-   metadata: {}
    name: ProductID
    nullable: true
    type: integer
-   metadata: {}
    name: ProductPhotoID
    nullable: true
    type: integer
-   metadata: {}
    name: Primary
    nullable: true
    type: boolean
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: _corrupt_record
    nullable: true
    type: string
type: struct
