fields:
-   metadata: {}
    name: ProductModelID
    nullable: true
    type: integer
-   metadata: {}
    name: ProductDescriptionID
    nullable: true
    type: integer
-   metadata: {}
    name: CultureID
    nullable: true
    type: string
-   metadata: {}
    name: ModifiedDate
    nullable: true
    type: timestamp
-   metadata: {}
    name: _corrupt_record
    nullable: true
    type: string
type: struct
